## Example
    
    467..114..
    ...*......
    ..35..633.
    ......#...
    617*......
    .....+.58.
    ..592.....
    ......755.
    ...$.*....
    .664.598..
    In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

In [1]:
S="""
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
""".strip()

In [3]:
print(S)

467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..

In [8]:
lines=S.split('\n')
line=lines[0]
R=len(lines)
C=len(line)

In [9]:
line

'467..114..'

In [16]:
def neighbors(r,c):

    if c>0:
        yield r,c-1

        if r>0:
            yield r-1,c-1

        if r<R-1:
            yield r+1,c-1
    if c<C-1:
        yield r,c+1

        if r>0:
            yield r-1,c+1

        if r<R-1:
            yield r+1,c+1

    if r>0:
        yield r-1,c

    if r<R-1:
        yield r+1,c

In [13]:

data=[]
for row in range(R):
    locs=[]
    ss=''
    for col in range(C):
        character=lines[row][col]
        if character in '0123456789':
            ss+=character
            locs.append((row,col))
        elif ss:
            val=int(ss)
            data.append([val,locs])
            locs=[]
            ss=''
    if ss:
        val=int(ss)
        data.append([val,locs])

data

[[467, [(0, 0), (0, 1), (0, 2)]],
 [114, [(0, 5), (0, 6), (0, 7)]],
 [35, [(2, 2), (2, 3)]],
 [633, [(2, 6), (2, 7), (2, 8)]],
 [617, [(4, 0), (4, 1), (4, 2)]],
 [58, [(5, 7), (5, 8)]],
 [592, [(6, 2), (6, 3), (6, 4)]],
 [755, [(7, 6), (7, 7), (7, 8)]],
 [664, [(9, 1), (9, 2), (9, 3)]],
 [598, [(9, 5), (9, 6), (9, 7)]]]

In [15]:
print(S)

467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..

In [17]:
result=[]
for val, locs in data:
    found=False
    for r,c in locs:
        for rn,cn in neighbors(r,c):
            if lines[rn][cn] not in '0123456789.':
                found=True
                result.append(val)
                break
        if found:
            break
print(result)

[467, 35, 633, 617, 592, 755, 664, 598]

In [18]:
sum(result)

4361

## Part 1

In [19]:
S=open('data/day3.txt').read().strip()
lines=S.split('\n')
len(lines)

140

In [20]:
lines=S.split('\n')
line=lines[0]
R=len(lines)
C=len(line)

In [21]:

data=[]
for row in range(R):
    locs=[]
    ss=''
    for col in range(C):
        character=lines[row][col]
        if character in '0123456789':
            ss+=character
            locs.append((row,col))
        elif ss:
            val=int(ss)
            data.append([val,locs])
            locs=[]
            ss=''
    if ss:
        val=int(ss)
        data.append([val,locs])

In [23]:
result=[]
for val, locs in data:
    found=False
    for r,c in locs:
        for rn,cn in neighbors(r,c):
            if lines[rn][cn] not in '0123456789.':
                found=True
                result.append(val)
                break
        if found:
            break
print(sum(result))

543867

## Part 2

    Consider the same engine schematic again:
    
    467..114..
    ...*......
    ..35..633.
    ......#...
    617*......
    .....+.58.
    ..592.....
    ......755.
    ...$.*....
    .664.598..
    In this schematic, there are two gears. The first is in the top left; it has part numbers 467 and 35, so its gear ratio is 16345. The second gear is in the lower right; its gear ratio is 451490. (The * adjacent to 617 is not a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces 467835.

In [24]:
S="""
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
""".strip()

In [25]:
lines=S.split('\n')
line=lines[0]
R=len(lines)
C=len(line)

In [26]:

data=[]
for row in range(R):
    locs=[]
    ss=''
    for col in range(C):
        character=lines[row][col]
        if character in '0123456789':
            ss+=character
            locs.append((row,col))
        elif ss:
            val=int(ss)
            data.append([val,locs])
            locs=[]
            ss=''
    if ss:
        val=int(ss)
        data.append([val,locs])

In [33]:
from numpy import prod

In [34]:
total=0
for row in range(R):
    for col in range(C):
        character=lines[row][col]
        if not character=='*':
            continue

        vals=[]
        for val, locs in data:
            for rn,cn in neighbors(row,col):
                if (rn,cn) in locs:
                    vals.append(val)
                    break
        if len(vals)==2:
            print(vals)
            total+=prod(vals)


print(total)

[467, 35]
[755, 598]
467835

In [35]:
S=open('data/day3.txt').read().strip()
lines=S.split('\n')
len(lines)

140

In [36]:
lines=S.split('\n')
line=lines[0]
R=len(lines)
C=len(line)

In [37]:

data=[]
for row in range(R):
    locs=[]
    ss=''
    for col in range(C):
        character=lines[row][col]
        if character in '0123456789':
            ss+=character
            locs.append((row,col))
        elif ss:
            val=int(ss)
            data.append([val,locs])
            locs=[]
            ss=''
    if ss:
        val=int(ss)
        data.append([val,locs])

In [38]:
total=0
for row in range(R):
    for col in range(C):
        character=lines[row][col]
        if not character=='*':
            continue

        vals=[]
        for val, locs in data:
            for rn,cn in neighbors(row,col):
                if (rn,cn) in locs:
                    vals.append(val)
                    break
        if len(vals)==2:
            print(vals)
            total+=prod(vals)


print(total)

[401, 159]
[697, 896]
[656, 5]
[33, 717]
[335, 260]
[834, 29]
[815, 692]
[715, 531]
[688, 831]
[553, 447]
[129, 333]
[441, 982]
[586, 89]
[21, 494]
[12, 875]
[607, 133]
[529, 39]
[815, 804]
[703, 313]
[208, 480]
[659, 23]
[528, 877]
[602, 436]
[602, 37]
[354, 218]
[140, 410]
[707, 539]
[222, 896]
[516, 765]
[852, 68]
[24, 707]
[290, 152]
[598, 176]
[203, 682]
[926, 750]
[283, 878]
[395, 659]
[20, 641]
[534, 53]
[749, 776]
[337, 667]
[189, 257]
[648, 889]
[282, 739]
[901, 490]
[491, 543]
[997, 522]
[2, 250]
[316, 754]
[296, 142]
[673, 23]
[464, 937]
[179, 536]
[931, 703]
[640, 36]
[644, 875]
[551, 380]
[707, 658]
[920, 534]
[909, 289]
[251, 700]
[658, 196]
[882, 586]
[212, 428]
[993, 14]
[532, 309]
[685, 247]
[611, 416]
[403, 715]
[243, 670]
[22, 747]
[575, 2]
[539, 361]
[738, 277]
[137, 453]
[216, 153]
[35, 462]
[798, 157]
[459, 726]
[255, 122]
[302, 672]
[530, 862]
[269, 643]
[545, 385]
[727, 577]
[425, 743]
[267, 521]
[695, 642]
[700, 236]
[492, 820]
[333, 849]
[755, 610]
[856, 727]
[137, 839]
[489, 541]
[450, 449]
[479, 208]
[617, 547]
[971, 810]
[559, 410]
[237, 485]
[124, 841]
[641, 790]
[993, 911]
[853, 295]
[391, 83]
[614, 635]
[649, 138]
[201, 599]
[928, 618]
[67, 114]
[704, 4]
[608, 372]
[566, 111]
[423, 991]
[436, 985]
[278, 160]
[856, 96]
[135, 860]
[385, 640]
[69, 366]
[127, 350]
[772, 347]
[446, 341]
[250, 326]
[102, 595]
[292, 682]
[595, 289]
[75, 138]
[449, 62]
[650, 318]
[619, 264]
[893, 675]
[890, 659]
[79, 263]
[118, 405]
[245, 651]
[806, 134]
[993, 443]
[834, 287]
[75, 562]
[334, 25]
[352, 90]
[986, 694]
[27, 102]
[89, 453]
[775, 732]
[123, 700]
[573, 203]
[928, 607]
[87, 875]
[186, 223]
[709, 519]
[205, 272]
[579, 811]
[149, 931]
[814, 214]
[228, 563]
[965, 817]
[221, 796]
[292, 942]
[594, 488]
[365, 974]
[29, 519]
[79, 93]
[592, 454]
[170, 947]
[507, 712]
[490, 824]
[184, 381]
[971, 181]
[338, 167]
[923, 935]
[430, 587]
[228, 464]
[597, 733]
[471, 414]
[215, 717]
[794, 715]
[908, 664]
[210, 390]
[845, 130]
[66, 564]
[544, 715]
[781, 390]
[576, 847]
[781, 716]
[356, 447]
[169, 306]
[466, 228]
[459, 714]
[324, 109]
[943, 832]
[198, 934]
[629, 961]
[178, 489]
[507, 533]
[897, 412]
[440, 778]
[700, 952]
[437, 927]
[359, 618]
[534, 929]
[667, 874]
[443, 947]
[385, 435]
[861, 88]
[51, 226]
[545, 107]
[245, 943]
[284, 302]
[190, 381]
[640, 327]
[790, 70]
[244, 617]
[349, 95]
[901, 104]
[733, 149]
[230, 569]
[916, 634]
[297, 933]
[230, 421]
[925, 659]
[577, 860]
[529, 658]
[253, 617]
[852, 908]
[911, 269]
[11, 931]
[885, 906]
[589, 470]
[915, 734]
[737, 502]
[720, 854]
[716, 226]
[874, 603]
[326, 71]
[284, 795]
[971, 53]
[303, 134]
[554, 225]
[808, 690]
[258, 951]
[890, 30]
[314, 468]
[86, 87]
[663, 694]
[513, 243]
[31, 712]
[275, 119]
[888, 408]
[162, 922]
[995, 356]
[870, 552]
[46, 153]
[66, 466]
[803, 638]
[519, 511]
[520, 859]
[238, 678]
[503, 429]
[306, 546]
[239, 406]
[173, 636]
[708, 534]
[240, 860]
[498, 163]
[716, 851]
[55, 396]
[20, 197]
[980, 999]
[794, 155]
[722, 172]
[408, 727]
[109, 167]
[482, 725]
[346, 759]
[325, 720]
[322, 641]
[98, 178]
[74, 467]
[783, 699]
[32, 673]
[54, 525]
[171, 560]
[214, 606]
[835, 969]
[240, 168]
[982, 395]
[838, 744]
[840, 257]
[43, 842]
[48, 983]
[880, 157]
[420, 578]
[833, 193]
[586, 156]
[78, 93]
[922, 993]
[350, 556]
[698, 322]
[643, 384]
[675, 863]
[314, 91]
[170, 462]
[427, 506]
[959, 737]
[930, 634]
[972, 492]
[340, 950]
[298, 382]
[968, 701]
[498, 993]
[824, 832]
[248, 662]
[448, 930]
[965, 30]
[333, 355]
[565, 239]
[115, 484]
[967, 664]
79613331